WorldLibrary.Web/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Vereyon.Web;
using WorldLibrary.Web.Data;
using WorldLibrary.Web.Data.Entities;
using WorldLibrary.Web.Enums;
using WorldLibrary.Web.Helper;
using WorldLibrary.Web.Models;
using WorldLibrary.Web.Repositories;

namespace WorldLibrary.Web.Controllers
{
    
    public class BooksController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IAssessmentRepository _assessmentRepository;
        private readonly IUserHelper _userHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IMailHelper _mailHelper;
        private readonly IFlashMessage _flashMessage;
        private readonly DataContext _context;

        public BooksController(IBookRepository bookRepository,
            IAssessmentRepository assessmentRepository,
            IUserHelper userHelper,
            IBlobHelper blobHelper,
            IConverterHelper converterHelper,
            IMailHelper mailHelper,
            IFlashMessage flashMessage,
            DataContext context)
        {
            _bookRepository = bookRepository;
            _assessmentRepository = assessmentRepository;
            _userHelper = userHelper;
            _blobHelper = blobHelper;
            _converterHelper = converterHelper;
            _flashMessage = flashMessage;
            _mailHelper = mailHelper;
            _context = context;
        }

        // GET: Books
        public IActionResult Index()
        {
            return View(_bookRepository.GetAll().OrderBy(b => b.Title));
        }

        // GET: Books/Details/5
        [Route("details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("BookNotFound");
            }

            var book = await _bookRepository.GetByIdAsync(id.Value);
            if (book == null)
            {
                return new NotFoundViewResult("BookNotFound");
            }

            return View(book);
        }
       
        // GET: Books/Create
        [Route("create")]
     
        public IActionResult Create()
        {
            var model = new BookViewModel
            {
                Assessments = _assessmentRepository.GetComboAssessment()
            };
            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create")]

        public async Task<IActionResult> Create(BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                Guid imageId = Guid.Empty;

                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "books");
                }

                Guid imagePdf = Guid.Empty;
                if (model.BookPdf != null && model.BookPdf.Length > 0)
                {
                    imagePdf = await _blobHelper.UploadBlobAsync(model.BookPdf, "pdfs");
                }

                var book = _converterHelper.ToBook(model, imageId, imagePdf, true);
                book.Assessment = model.AssessmentId.ToString();
                book.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                await _bookRepository.CreateAsync(book);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }


        // GET: Books/Edit/5
        [Route("edit")]
        [Authorize(Policy = "LibrarianOrAssistant")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("BookNotFound");
            }

            var book = await _bookRepository.GetByIdAsync(id.Value);
            if (book == null)
            {
                return new NotFoundViewResult("BookNotFound");
            }
            
            var model = _converterHelper.ToBookViewModel(book);
            model.Assessments = _assessmentRepository.GetComboAssessment();
            return View(model);
        }


        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("edit")]
        public async Task<IActionResult> Edit(BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    if (model.Quantity != 0 && model.StatusBook == StatusBook.Available)
                    {
                        var response = await _bookRepository.EditBookAsync(model, this.User.Identity.Name);
                        
                        foreach (var customer in model.Customers)
                        {
                            _mailHelper.SendEmail(customer.Email,
                             "Book Available", $"<h1>Book World Library</h1>" +
                              $"Dear {customer.FullName}, " +
                              $"The book {response.Title} is now available again</br></br>" +
                              "<p>To make a reservation, visit our website</p>");
                        }

                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _bookRepository.ExistAsync(model.Id))
                    {
                        return new NotFoundViewResult("BookNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Books/Delete/5
        [Route("delete")]
        [Authorize(Roles ="Librarian, Assistant")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("BookNotFound");
            }

            var book = await _bookRepository.GetByIdAsync(id.Value);
            if (book == null)
            {
                return new NotFoundViewResult("BookNotFound");
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _bookRepository.GetByIdAsync(id);
            try
            {
                await _bookRepository.DeleteAsync(book);
                return RedirectToAction(nameof(Index));

            }
            catch (DbUpdateException ex)
            {

                if (ex.InnerException 
                    != null && ex.InnerException.Message.Contains("DELETE"))
                {
                    ViewBag.ErrorTitle = $"{book.Title} probably in been used!!!";
                    ViewBag.ErrorMessage = $"{book.Title} can not be deleted because there are reserves with this book.</br></br>" +
                        $"First delete all the reserves with this book" +
                        $" and please try again delete it!";

                }

                return View("Error");
            }
        }
        [Route("download")]
        //criar
        public async Task<IActionResult> DownloadPdf(BookViewModel model)
        {
             var user = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);

            bool librarian = await _userHelper.IsUserInRoleAsync(user, "Librarian");
            bool asssitant = await _userHelper.IsUserInRoleAsync(user, "Assistant");
            var book = _context.Books
               .Where(b => b.Id == model.Id)
               .FirstOrDefault();
           if(librarian == true || asssitant == true)
           {
                if (book.ImagePdf == Guid.Parse("00000000-0000-0000-0000-000000000000"))
                {
                    _flashMessage.Info("There is no book online");
                    return View();
                }
                
                var pdf = _blobHelper.DownloadBlobPdfAsString(model.Id);
                string base64String = Convert.ToBase64String(pdf.Result);
                string dataUrl = $"data:application/pdf;base64,{base64String}";
                ViewBag.PdfUrl = dataUrl;
                return View();
           }
               

            var customer = _context.Customers
                .Include(c => c.User)
                .Where(c => c.User.UserName == this.User.Identity.Name)
                .FirstOrDefault();
            if(customer == null) 
            {
                _flashMessage.Info("Access denied!!!" +                    
                    "Please became premium first!");
                return View();


            }
            if (customer.Premium == null) 
            {
                _flashMessage.Info("Access denied!!!" +
                    "Please became premium first!");
                return View();

            }
            if (book.ImagePdf == Guid.Parse("00000000-0000-0000-0000-000000000000"))
            {
                _flashMessage.Info("There is no book online");
                return View();
            }

WorldLibrary.Web/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Vereyon.Web;
using WorldLibrary.Web.Data;
using WorldLibrary.Web.Helper;
using WorldLibrary.Web.Models;
using WorldLibrary.Web.Repositories;

namespace WorldLibrary.Web.Controllers
{
    public class ContactsController : Controller
    {
        public readonly DataContext _context;
        public readonly ICustomerRepository _customerRepository;
        public readonly IEmployeeRepository _employeeRepository;
        public readonly IMailHelper _mailHelper;
        public readonly IFlashMessage _flashMessage;
        public readonly IUserHelper _userHelper;
        public ContactsController(
              DataContext context,
              ICustomerRepository customerRepository,
              IEmployeeRepository employeeRepository,
              IMailHelper mailHelper,
              IUserHelper userHelper,
              IFlashMessage flashMessage)
        {
            _context = context;
            _customerRepository = customerRepository;
            _employeeRepository = employeeRepository;
            _mailHelper = mailHelper;
            _flashMessage = flashMessage;
            _userHelper = userHelper;
        }
        public IActionResult Index()
        {
            var model = new ContactViewModel
            {

                Employees = _employeeRepository.GetComboEmployeesEmail(),
            };
            return View(model);
        }

        public IActionResult SendMail(ContactViewModel model)
        {

            Response response = _mailHelper.SendEmail(model.Email, model.Subject, model.Message);
            _context.Contacts.Add(model);
            _context.SaveChangesAsync();
            if (response.IsSuccess)
            {

                _flashMessage.Confirmation("The email was sent successfully!!!");
                return RedirectToAction("Index");

            }

            return RedirectToAction("Index");


        }
        [Route("externalcontact")]
        public IActionResult ExternalContact()
        {
            var model = new ContactViewModel
            {
                Customers = _customerRepository.GetComboCustomersEmail(),

            };
            return View(model);
        }

        [HttpPost]
        [Route("externalcontact")]
        public IActionResult ExternalContact(ContactViewModel model)
        {
            Response response = _mailHelper.SendEmail(model.Email, model.Subject, model.Message);
            _context.Contacts.Add(model);
            _context.SaveChangesAsync();
            if (response.IsSuccess)
            {

                _flashMessage.Confirmation("The email was sent successfully!!!");
                model = new ContactViewModel
                {
                    Customers = _customerRepository.GetComboCustomersEmail(),

                };
                return View(model);

            }

            model = new ContactViewModel
            {
                Customers = _customerRepository.GetComboCustomersEmail(),

            };
            return View(model);
        }
        [Route("contact")]
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        [Route("contact")]
        
        public IActionResult Contact(ContactViewModel model)
        {


            Response response = _mailHelper.SendEmail("romeupires@yopmail.com", model.Subject, model.Message);

            _context.Contacts.Add(model);
            _context.SaveChangesAsync();
            if (response.IsSuccess)
            {

                _flashMessage.Confirmation("The email was sent successfully!!!");
                return RedirectToAction("Index");

            }

            return RedirectToAction("Index");
        }
    }
}

WorldLibrary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>World Library</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:500,800" rel="stylesheet">
    

@*    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>*@


</head>

<body class="main-layout home_page">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="images/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                            <div class="center-desk">
                                <div class="logo"> <a href="index.html"><img src="images/wl-logo.png" alt="#"></a> </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                        <div class="menu-area">
                            <div class="limit-box">
                                <nav class="main-menu">
                                    <ul class="menu-area-main">
                                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                                        <li><a asp-controller="Books" asp-action="Index">Books</a></li>
                                        <li><a asp-controller="PhysicalLibraries" asp-action="Index">Physical Libraries</a></li>
                                        <li><a asp-controller="Contacts" asp-action="Contact">Contact</a></li>
                                        <li><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                                        {
                                            <li>
                                                <a style="color:white">Admin</a>
                                                <ul class="submenu">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="RegisterRole">Register New Role</a>
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="PhysicalLibraries" asp-action="Index">Physical Libraries</a>
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Countries" asp-action="Index">Countries and Cities</a></li>
                                                </ul>
                                            </li>
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contact Form </a>
                                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Contacts" asp-action="Index">Internal contact</a></li>
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Contacts" asp-action="ExternalContact">External contact</a></li>
                                                </ul>
                                            </li>
                                        }
                                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Librarian"))
                                        {
                                            <li>
                                                <a style="color:white">Librarian</a>
                                                <ul class="submenu">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Forum">Forum</a>
                                                </ul>
                                            </li>
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contact Form </a>
                                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Contacts" asp-action="Index">Internal contact</a></li>
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Contacts" asp-action="ExternalContact">External contact</a></li>
                                                </ul>
                                            </li>
                                        }
                                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Assistant"))
                                        {
                                            <li>
                                                <a style="color:white">Assistant</a>
                                                <ul class="submenu">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                                                   
                                                </ul>
                                            </li>
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contact Form </a>
                                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Contacts" asp-action="Index">Internal contact</a></li>
                                                    <li><a class="dropdown-item" asp-area="" asp-controller="Contacts" asp-action="ExternalContact">External contact</a></li>
                                                </ul>
                                            </li>
                                        }
                                       

                                        @if (this.User.Identity.IsAuthenticated)
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Forum">Forum</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" asp-area="" asp-controller="Reserves" asp-action="Index">Reserves</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                            </li>
                                        }
                                        else
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                            </li>


                                        }
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- end header inner -->
  
    @RenderBody()
    @RenderSection("content", required: false)
   

    <!-- footer -->
    <footer>
        <div class="footer">
            <div class="container">
                <div class="row pdn-top-30">
                    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                        <div class="Follow">
                            <h3>Follow Us</h3>
                        </div>
                        <ul class="location_icon">
                            <li> <a href="https://www.facebook.com"><img src="icon/facebook.png"></a></li>
                            <li> <a href="https://www.twitter.com"><img src="icon/Twitter.png"></a></li>
                            <li> <a href="https://www.linkedin.com"><img src="icon/linkedin.png"></a></li>
                            <li> <a href="https://www.instagram.com"><img src="icon/instagram.png"></a></li>
                        </ul>
                    </div>
                    <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">
                        <div class="Follow">
                            <h3>Newsletter</h3>
                        </div>
                        <input class="Newsletter" placeholder="Enter your email" type="Enter your email">
                        <button class="Subscribe">Subscribe</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <partial name="_CookieConsentPartial" />
                <p>Version 1.0 2023 by Daiane Farias &amp; Evelyn Nunes </a></p>
            </div>
        </div>
    </footer>
    
    <!-- Javascript files-->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.0.0.min.js"></script>
    <script src="~/js/plugin.js"></script>
    <!-- sidebar -->
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/custom.js"></script>
     
  @await RenderSectionAsync("Scripts", required: false)
   
</body>
</html>